/**
 * Created by wangdi on 23/11/16.
 */
'use strict';

export const FETCH_HOME_DATA_SUCCESS = 'FETCH_HOME_DATA_SUCCESS';
export const FETCH_HOME_DATA_FAILURE = 'FETCH_HOME_DATA_FAILURE';
export const FETCH_HOME_DATE_REQUEST = 'FETCH_HOME_DATE_REQUEST';

export const FETCH_RANDOM_DATA_SUCCESS = 'FETCH_RANDOM_DATA_SUCCESS';
export const FETCH_RANDOM_DATA_FAILURE = 'FETCH_RANDOM_DATA_FAILURE';
export const FETCH_RANDOM_DATA_REQUEST = 'FETCH_RANDOM_DATA_REQUEST';
export const FETCH_RANDOM_MORE_DATA_SUCCESS = 'FETCH_RANDOM_MORE_DATA_SUCCESS';
export const FETCH_RANDOM_MORE_DATA_REQUEST = 'FETCH_RANDOM_MORE_DATA_REQUEST';
export const FETCH_RANDOM_MORE_DATA_FAILURE = 'FETCH_RANDOM_MORE_DATA_FAILURE';

export const FETCH_TARGET_DATA_SUCCESS = 'FETCH_TARGET_DATA_SUCCESS';
export const FETCH_TARGET_DATA_FAILURE = 'FETCH_TARGET_DATA_FAILURE';
export const FETCH_TARGET_DATA_REQUEST = 'FETCH_TARGET_DATA_REQUEST';
export const FETCH_TARGET_MORE_DATA_REQUEST = 'FETCH_TARGET_MORE_DATA_REQUEST';
export const FETCH_TARGET_MORE_DATA_FAILURE = 'FETCH_TARGET_MORE_DATA_FAILURE';
export const FETCH_TARGET_DATA_IS_FULL = 'FETCH_TARGET_DATA_IS_FULL';

export const UPDATE_STAR_LIST = 'UPDATE_STAR_LIST';
export const STAR_DATA_SUCCESS = 'STAR_DATA_SUCCESS';
export const UNSTAR_DATA_SUCCESS = 'UNSTAR_DATA_SUCCESS';
export const UPDATE_STAR_STATE = 'UPDATE_STAR_STATE';

export const CHANGE_COLOR = 'CHANGE_COLOR';
export const CHANGE_DISPLAY_ORDER = 'CHANGE_DISPLAY_ORDER';
export const OPEN_SHOW_THUMBNAIL = 'OPEN_SHOW_THUMBNAIL';
export const CLOSE_SHOW_THUMBNAIL = 'CLOSE_SHOW_THUMBNAIL';