/**
 * Created by wangdi on 23/11/16.
 */
'use strict';

export const RECEIVE_HOME_DATA = 'RECEIVE_HOME_DATA';
export const REQUEST_HOME_DATA = 'REQUEST_HOME_DATA';

export const FETCH_TARGET_DATA_SUCCESS = 'FETCH_TARGET_DATA_SUCCESS';
export const FETCH_TARGET_DATA_FAILURE = 'FETCH_TARGET_DATA_FAILURE';