/**
 * Created by wangdi on 23/11/16.
 */
'use strict';

export const FETCH_HOME_DATA_SUCCESS = 'FETCH_HOME_DATA_SUCCESS';
export const FETCH_HOME_DATA_FAILURE = 'FETCH_HOME_DATA_FAILURE';
export const FETCH_HOME_DATE_REQUEST = 'FETCH_HOME_DATE_REQUEST';

export const FETCH_TARGET_DATA_SUCCESS = 'FETCH_TARGET_DATA_SUCCESS';
export const FETCH_TARGET_DATA_FAILURE = 'FETCH_TARGET_DATA_FAILURE';
export const FETCH_TARGET_DATA_REQUEST = 'FETCH_TARGET_DATA_REQUEST';
export const FETCH_TARGET_MORE_DATA_REQUEST = 'FETCH_TARGET_MORE_DATA_REQUEST';
export const FETCH_TARGET_DATA_IS_FULL = 'FETCH_TARGET_DATA_IS_FULL';

export const CHANGE_COLOR = 'CHANGE_COLOR';